### ISSUE TITLE
Add tests for http healthchecks

### ISSUE THREAD

**Issue by FedericoPonzi** [FedericoPonzi/Horust#10]
Adds some tests for the http based healthchecks.

**Comment by rajkumarGosavi** [comment]
Hi i would like to contribute. I have recently completed The Rust Book and have some development experience.

**Comment by FedericoPonzi** [comment]
Hi @rajkumarGosavi and thanks for your interest!
Let me briefly describe the quest:
This is the healthchecker: https://github.com/FedericoPonzi/Horust/blob/master/src/horust/healthcheck.rs
Healthchecks are either file based, or http based (as described [here](https://github.com/FedericoPonzi/Horust/blob/master/DOCUMENTATION.md#healthiness-check)).
Right now, there are only tests for the [file based](https://github.com/FedericoPonzi/Horust/blob/master/src/horust/healthcheck.rs#L169) check.
So you should:
1. Create a new test for the http based healthcheck
2. Define a new [Healthiness](https://github.com/FedericoPonzi/Horust/blob/master/src/horust/healthcheck.rs#L175) struct with a randome http_endpoint, run the healthcheck and assert it fails the healthcheck.
3. Spawn an http server on a random port, keep that port and use it for the definition of the `[Healthiness](https://github.com/FedericoPonzi/Horust/blob/master/src/horust/healthcheck.rs#L175)` struct.
4. Assert that now the healthiness is successful.

For the http server, you can have a look at hyper. I'm not sure if reqwest can be used for spawning a server.
If you would like to tackle this issue, please reply and I'll assign it to you.

**Comment by rajkumarGosavi** [comment]
Hi i have written a test for http healthcheck. i have given test http endpoint as http://localhost:8080 .
Should I run something on that port?

**Comment by FedericoPonzi** [comment]
No, the only requirement is that it should respond with an HTTP 200.

**Comment by rajkumarGosavi** [comment]
Ok i have spawned a server and have done `assert!(!healthchecks(&healthiness));`

But it fails do i have to write a new helper to actually hit the server at a given route and get the header from the response?
Or is it already written?

**Comment by FedericoPonzi** [comment]
> Ok i have spawned a server and have done `assert!(!healthchecks(&healthiness));`
> 
> But it fails do i have to write a new helper to actually hit the server at a given route and get the header from the response?
> Or is it already written?

This discussion might be easier if you open a PR, and we can discuss from there (so I can see the code). The request should be sent to Healthiness.http_endpoint form https://github.com/FedericoPonzi/Horust/blob/master/src/horust/healthcheck.rs#L55. This should check the response code and use that to determine if the test was successful or not. If you could kindly open a PR I can also provide more insight.

**Comment by rajkumarGosavi** [comment]
I am setting up a non blocking TcpListener but it is giving me `Resource not available error`. I am not using hyper as it needs function to be asnyc and tests cannot be async. Give me some time to figure it out else i will reach out

**Comment by FedericoPonzi** [comment]
Well, technically if we include tokio then we could use `tokio-test` for having async tests, but I would rather not unless there is no other way around it or it is also needed elsewhere.

Instead of the tcp listener, you could use [rouille](https://crates.io/crates/rouille) for spawning a sync http server.

**Comment by rajkumarGosavi** [comment]
Yes I did it using TcpListener and TcpStream. Now i just need to randomize the port. Will push soon

**Comment by rajkumarGosavi** [comment]
@FedericoPonzi please check latest commit
