### ISSUE TITLE
Run specified services only

### ISSUE THREAD

**Issue by Bessonov** [FedericoPonzi/Horust#106]
Currently, there are two ways to run something:
- `<command>`: run single command
- `--services-path`: run all services from a path

But it's missing something like `--services-file` or `--service-configuration` to run specified services only. My use case: I build an "self-contained" image with frontend, backend and auxiliary services. On the test system all services should run. But for production only backend and auxiliary services are relevant. I can workaround it by creating multiple "services-path" directories, but it would be nice just specify multiple service configurations.

Or probably better, if `--services-path` could accept wildcards like:
- `--services-path /dir/*`: all services inside `/dir`. Maybe also same as `--services-path /dir` to maintain compatibility
- `--services-path /dir/**`: all services inside `/dir` and children
- `--services-path /dir/backend.toml`: only backend service

WDYT?

**Comment by FedericoPonzi** [comment]
Looks reasonable to me. This would improve over #55.
