### ISSUE TITLE
Usability as a crate?

### ISSUE THREAD

**Issue by bryanlarsen** [FedericoPonzi/Horust#172]
I currently have a rust program that starts another via Popen.  I need to do better than that, like restart on crash with backoff, et cetera.   Not difficult, but I'm sure there are edge cases I'd miss if I reinvented the wheel.   Horust looks like it's solved a lot of this stuff, so it'd be nice to use it.

After a 30 second glance at docs.rs and the code the sort of thing I'd be looking for would be a way to instantiate Horus with a Service or list of Service's rather than a service file, and an interface to restart and/or reload a service.

Is this the sort of thing that'd be easy for me to add to Horust, or should I look elsewhere?

**Comment by FedericoPonzi** [comment]
Hi Bryan,
Horust was not designed with this use case in mind, but I think it should definitely possible to do it. If you feel like you're missing visibility or a better interface, feel free to open a pr or an issue with some suggestion! Thanks
