### ISSUE TITLE
Default working directory for services is not useful

### ISSUE THREAD

**Issue by hanshuebner** [FedericoPonzi/Horust#210]
#### Description:

Horust currently uses "/" as working directory for services that have no `working-directory` specified.  It would be more useful if the working directory defaulted to the working directory of the Horust process.  That way, when not running in a container, it would be easier to reference e.g. configuration files passed to services as relative paths (i.e. `command = "foo -c foo.conf").  Before coming up with a PR, I would like to know whether it was a conscious decision to default to "/".

**Comment by FedericoPonzi** [comment]
I think / or horust's wd would work fine if the user doesn't care about the wd. The risk is impossibility to unmount a used filesystem.
