### ISSUE TITLE
Option for setting threshold for failed healthchecks

### ISSUE THREAD

**Issue by FedericoPonzi** [FedericoPonzi/Horust#36]
This issue is for fixing this todo: https://github.com/FedericoPonzi/Horust/blob/master/src/horust/healthcheck/mod.rs#L48

Right now if more than 2 healthchecks in a row fail, the service will be killed. This might be too much aggressive for some programs, and not enough aggressive for others. 
It would be nice to have in the [healthiness](https://github.com/FedericoPonzi/Horust/blob/master/DOCUMENTATION.md#healthiness-check) section of the config a parameter for setting the max failed amount of requests in a row before the service is killed.

**Comment by tomgs** [comment]
Mine! :)
Please assign me, if possible, will deal with this in the next few days.
