### ISSUE TITLE
Serde build error

### ISSUE THREAD

**Issue by esavier** [FedericoPonzi/Horust#52]
There is an issue with upstream serde. 1.0.119 (works with `serde = {version = "=1.0.118", features = ["derive"] }`

Horust is using serde::export and this module was renamed in serde 1.0.119. 
problematic files:
src/horust/formats/service.rs
src/lib.rs

**Comment by esavier** [comment]
this issue prevents users from doing `cargo install horust`

**Comment by FedericoPonzi** [comment]
I've removed the (*silly*) imports I was using, and bumped a new release on crates.io. I've tried to run `cargo install horust` in a docker container and it works fine now! Thanks for raising this issue! I will also try to create a release on github + new docker version for ease usage.
