### ISSUE TITLE
Termitate all services immediately when user press CTRL+C second time.

### ISSUE THREAD

**Issue by frondeus** [FedericoPonzi/Horust#54]
It is common in other CLI similar to Horust, to gracefully stop all services on first `CTRL+C`, but terminate it immediately on following signals.

I'd expect similar behavior in Horust, especially for local-dev environment purposes where graceful-stop is not always necessary.

Of course, I could just prepare another service configuration for that purpose, but I think this is a justified case to implement this enhancement.

I'm willing to dig into signal handling in Horust and prepare PR if you accept it.

**Comment by FedericoPonzi** [comment]
This is a great proposal, thanks! I'm thinking that the scenario you have in mind is very common in situation where Horust is run in "interactive" way (e.g. not in background). Assuming it was called without a terminal what do you think it should do in that case? Still kill everything after the second SIGTERM?

**Comment by frondeus** [comment]
I'd say - yes. If someone tries to kill a service with multiple signals, then probably there is an urge to do it as soon as possible. For example in case when there is memory leak and host is close to OOM errors, or application started generating too many logs eating all disk space (or inodes) - then the time is precious enough to kill services immediately.

I'll leave it for now so others can veto it.

**Comment by FedericoPonzi** [comment]
That sounds good to me and appreciate the consistency of behaviour. I think we can agree on the behaviour you described, and if needed it can be revised later on if anyone brings some good points to change it.
