### ISSUE TITLE
Allow Horust to load services from multiple directories

### ISSUE THREAD

**Issue by frondeus** [FedericoPonzi/Horust#55]
When I run my services under Horust supervision, I often split them under different categories. For example, "Services that are core for my stack" or "Extra services that are optional".

These services often need to run in parallel. Both "Extra" ones and "Core", because one depends on another. I don't want to run ALL services by providing a root directory (for example, "Another Extra service pack" I don't want to run in one scenario).

For now, I was just using two different instances of Horust to do the job. One for core and another for dependent services.

But do I have to?

I could ( I guess, I have never tried to be honest ) use symlinks and link core services to dependent services.

Or I could extend Horust to accept more than one directory path, merge fetched services into one vector and pass it to validation, and then create one single instance of Horust to rule them all :)

Service `docker-compose` can read multiple `docker-compose.yml` by accepting multiple `-f docker-compose-1.yml -f docker-compose-2.yml` etc.

I think (thanks to StructOpt) it is trivial to implement such behavior in Horust. 
It wouldn't be a breaking change (Horust would still accept a single argument), and it would make my life much easier.

Example:
```
horust --service-path ./services/core --service-path ./services/extra
```

**Comment by FedericoPonzi** [comment]
The example looks neat! Because you already have an open PR I'll assign this to you. Thanks!
