### ISSUE TITLE
List of shutdown signals is incomplete

### ISSUE THREAD

**Issue by moqmar** [FedericoPonzi/Horust#61]
#### Version Information:
* Version: 0.1.2 (built from latest master at 5dba1c2)
* Alpine Linux 3.13 container running on Docker

#### Description:
I was trying to shut down Apache2 gracefully by sending it a "SIGWINCH" (as for whatever reason that's the signal they decided on for that), but I'm getting the following error when setting `signal = "WINCH"` as it's not part of the list of allowed signals:

```
Failed loading toml file: /etc/horust/services/apache2.toml
    
    Caused by:
        unknown variant `WINCH`, expected one of `TERM`, `HUP`, `INT`, `QUIT`, `USR1`, `USR2` for key `termination.signal` at line 10 column 1
```

Maybe it would be possible to also allow an integer for the `signal` option, or to add all available signals there?

**Comment by FedericoPonzi** [comment]
Hey Moritz, thanks for reporting this. 

I would rather not use an integer and instead add all the missing signal mappings. I think it makes for a nicer UX.

I believe the currently supported are the "most common" signals used for termination, but I guess `WINCH` should be there. I'm going to add it right away. Do you feel like there is any other signal that should be included in the list?

**Comment by moqmar** [comment]
Oh, thanks for fixing this so quickly! I'd say just adding [all possible signals](https://docs.rs/nix/0.20.0/nix/sys/signal/enum.Signal.html) would fix other related issues and not cause any harm.
