### ISSUE TITLE
Why horuseye? 

### ISSUE THREAD

**Issue by osevan** [FedericoPonzi/Horust#77]
Any connections to occultist society?

I am the only person who worries when there are Egyptian mythological deities,
get involved in a linux init starter?

what about allusions to sects like illuminati and horus eye, who want to enslave the world with Bill Gates and Klaus Schwab and Elon musk?

**Comment by esavier** [comment]
don't you have anything better to do?
Issues are meant to be technology related, if you want to discuss politics, please, visit reddit
